export const products = [
  { id: 1, image: '/media/eco-1.png', title: 'Modern UI Kit', description: 'A sleek and modern UI kit for web apps.', price: 29.99, category: 'UI' },
  { id: 2, image: '/media/icon-6.jpg', title: 'Essential Icon Set', description: '200 essential icons for all your needs.', price: 19.99, category: 'Icons' },
  { id: 3, image: '/media/eco-2.png', title: 'E-Commerce UI Kit', description: 'A customizable E-Commerce UI kit.', price: 39.99, category: 'UI' },
  { id: 4, image: '/media/icon-9.jpg', title: 'Flat Icon Pack', description: 'Colorful flat icons for creative projects.', price: 14.99, category: 'Icons' },
  { id: 5, image: '/media/eco-3.png', title: 'Minimal UI Kit', description: 'A minimal UI kit for clean designs.', price: 24.99, category: 'UI' },
  { id: 6, image: '/media/icon-9.jpg', title: 'Line Icon Set', description: '100 line-style icons for modern designs.', price: 9.99, category: 'Icons' },
  { id: 7, image: '/media/health-1.png', title: 'Creative UI Kit', description: 'A vibrant UI kit for unique interfaces.', price: 34.99, category: 'UI' },
  { id: 8, image: '/media/icon-10.png', title: 'Social Media Icons', description: 'Icons for all popular social media platforms.', price: 12.99, category: 'Icons' },
  { id: 9, image: '/media/health-2.png', title: 'E-commerce UI Kit', description: 'A UI kit for online shopping platforms.', price: 49.99, category: 'UI' },
  { id: 10, image: '/media/icon1.png', title: 'Emoji Icon Set', description: 'Fun and expressive emoji icons.', price: 7.99, category: 'Icons' },
  { id: 11, image: '/media/health-3.jpg', title: 'Pro UI Kit', description: 'A professional UI kit for enterprise apps.', price: 59.99, category: 'UI' },
  { id: 12, image: '/media/icon2.jpg', title: 'Tech Icon Pack', description: 'Icons for tech and IT-related projects.', price: 15.99, category: 'Icons' },
  { id: 13, image: '/media/product-2.jpg', title: 'E-wallet Panel UI Kit', description: 'A UI kit for E-Wallet dashboards.', price: 44.99, category: 'UI' },
  { id: 14, image: '/media/icon3.png', title: 'Weather Icons', description: 'A pack of weather-related icons.', price: 10.99, category: 'Icons' },
  { id: 15, image: '/media/product3.jpg', title: 'Modern Design Kit', description: 'A UI kit for modern websites.', price: 39.99, category: 'UI' },
  { id: 16, image: '/media/icon4.png', title: 'Maps Icon Set', description: 'Icons for maps and navigation apps.', price: 11.99, category: 'Icons' },
  { id: 17, image: '/media/ui1.png', title: 'Advanced Creative UI', description: 'A premium UI kit for creatives.', price: 54.99, category: 'UI' },
  { id: 18, image: '/media/icon5.png', title: 'Finance Icons', description: 'Icons for finance and banking apps.', price: 18.99, category: 'Icons' },
  { id: 19, image: '/media/ui2.jpg', title: 'Blog UI Kit', description: 'A UI kit for blogging platforms.', price: 27.99, category: 'UI' },
  { id: 20, image: '/media/icon7.jpg', title: 'Media Icon Pack', description: 'Icons for media and entertainment.', price: 14.49, category: 'Icons' },
  { id: 30, image: '/media/icon8.jpg', title: 'Travel Icons', description: 'Icons for travel and tourism apps.', price: 16.99, category: 'Icons' },
];
